services:
  etcd:
    image: bitnami/etcd:3.5.12
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
  dns-service:
    image: docker.io/isilincoln/avoid-dns-service
    volumes:
      - ./configfiles/etcd.yml:/etc/avoid/config.yml
