services:
  etcd:
    image: bitnami/etcd:3.5.12
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
  dns-service:
    image: docker.io/isilincoln/avoid-dns-service
    volumes:
      - ./configfiles/etcd.yml:/etc/avoid/config.yml
  coredns:
    image: docker.io/isilincoln/avoid-coredns
    volumes:
      - ./configfiles/Corefile:/etc/coredns/Corefile
      - ./configfiles/avoid.zone:/etc/coredns/avoid.zone
    command: /coredns/coredns --cfg /etc/coredns/Corefile
