services:
  etcd:
    image: bitnami/etcd:3.5.12
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
  dns-service:
    image: docker.io/isilincoln/avoid-dns-service
    volumes:
      - ./configfiles/both.yml:/etc/avoid/config.yml
    environment:
      - DEBUG=yes
    ports:
      - "9000:9000"
    links:
      - "etcd:db"
  coredns:
    image: docker.io/isilincoln/avoid-coredns
    volumes:
      - ./configfiles/Corefile:/etc/coredns/Corefile
      - ./configfiles/avoid.zone:/etc/coredns/avoid.zone
    command: /coredns/coredns -conf /etc/coredns/Corefile
    links:
      - "dns-service:avoid"
